# Generated by Django 4.2.7 on 2025-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='carrier_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='home_terminal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
